# Generated by Django 3.1.3 on 2020-11-24 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201123_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+77999999999'. Up to 11 digits allowed.", regex='77\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
